---
- name: Variables Demo 
  hosts: g1
  become: yes
  vars:
  myusername: Fakinjayeju

  tasks:
  - name: update Dynamic page
    template: 
      src: dynamic.j2
      dest: /var/www/html/static.html
...